config/routes.rb
Rails.application.routes.draw do
  	
  	devise_for :owners
 	devise_for :customers
 	
	root  'places#index'
	
	resources :places do
    resources :comments, only: [:create, :destroy]
    resources :reservations, only: [:create, :destroy]
  	end
  	
	resources :categories, only: [:show, :index]
	#get 'places/new', to: 'places#new'
	#get 'places', to: 'places#index'
	#get 'places/:id', to: 'places#show', as:"place"
	#post 'places', to: 'places#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :places
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :place
	belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :comments 
   has_many :reservations, dependent: :destroy

end

app/models/owner.rb
class Owner < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :places, dependent: :destroy
end

app/models/place.rb
# == Schema Information
#
# Table name: places
#
#  id             :integer          not null, primary key
#  name           :string
#  address        :string
#  phone_number   :string
#  contact_mail   :string
#  established_at :date
#  description    :text
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Place < ApplicationRecord
	validates :name, :address, presence: true
	validates :phone_number, numericality: {only_integer: true}
	validates_format_of :contact_mail, :with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/

	validate :check_established_at
    
    belongs_to :category
	has_many :comments, dependent: :destroy
	belongs_to :owner
	has_many :reservations, dependent: :destroy
	
	private

	def check_established_at
		if established_at.present? && established_at >= Date.today
			errors.add(:established_at, "Kuruluş tarihi gecelek veya bugün olamaz!!")
		end
	end
	
end

app/models/reservation.rb
class Reservation < ApplicationRecord
	belongs_to :customer
	belongs_to :place
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  	@categories = Category.all
  end

  def show
  	@category = Category.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  before_action :authenticate_customer!
	before_action :set_place
	before_action :set_comment, only: [:destroy]
	before_action :authorize_customer!, only: [:destroy]


	def create 
		@comment = @place.comments.new(comment_params)
    @comment.customer = current_customer
		if @comment.save
      	redirect_to @place, notice: "Comment was saved"
    else
      	redirect_to @place, notice: "Comment couldn't saved"
    end
	end

	def destroy
    @comment.destroy
    redirect_to @place, notice: "Comment was deleted"
  end

	private

	def set_comment
  	@comment = Comment.find(params[:id])
	end

	def authorize_customer!
  	redirect_to @place, notice: "Not authorized" unless @comment.customer_id == current_customer.id
	end

	def comment_params
  	params.require(:comment).permit(:body)
	end

	def set_place
  	@place = Place.find(params[:place_id])
	end


end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
	before_action :authenticate_owner!, except: [:show, :index]
	before_action :set_place, only: [:show, :update, :edit, :destroy]
	before_action :authorize_owner!, only: [:edit, :update, :destroy]

	def new
		@place = Place.new
		load_categories
	end

	def index
		@places = Place.all.order(:id)
	end

	def show
	end

	def create 
		@place = current_owner.places.new(place_params)

		if @place.save
			flash[:success] = 'İşlem başarıyla tamamlandı'
			redirect_to place_path(@place)
		else
			load_categories
			render :new
		end
	end

	def edit
		load_categories
	end

	def update
		if @place.update(place_params)
			redirect_to place_path(@place)
		else
			load_categories
			render :edit
		end
	end

	def destroy
		@place.destroy
		redirect_to places_path
	end

	private

	def authorize_owner!
    	redirect_to root_path, notice: "Not authorized" unless @place.owner_id == current_owner.id
  	end

	def load_categories
		@categories = Category.all.collect {|c| [c.name, c.id]}
	end

	def set_place
		@place = Place.find(params[:id])
	end

	def place_params
		params.require(:place).permit(:name, :address, :phone_number, :contact_mail, :established_at, :description, :category_id)
	end
	
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
	before_action :authenticate_customer!
	before_action :set_place

	 def create
	    @reservation = @place.reservations.new(reserv_params) 
	    @reservation.customer = current_customer

	    if @reservation.save
	      redirect_to @place, notice: "Reservation was saved."
	    else
	      redirect_to @place, notice: "Reservation is not valid."
	    end
  	end

  	def destroy
	    @reservation.destroy
	    redirect_to @place, notice: "Comment was deleted"
  	end

	private
	def set_place
		@place = Place.find(params[:place_id])
	end

	def reserv_params
		params.require(:reservation).permit(:date, :number_of_people, :customer_id, :place_id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/application/_flash.html.erb
<% if !flash.empty? %>
  <div id="flash">
    <% flash.keys.each do |k| %>
      <div class="<%= k %>">
        <%= flash[k] %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/categories/index.html.erb
<h1>Listing Categories</h1>

<% @categories.each do |c| %>
	<li>
	<%= link_to c.name, category_path(c) %><br/><br/>
	</li>
<%end%>

<br/><%= link_to "Back to place list", places_path %>

app/views/categories/show.html.erb
<h1> <%= @category.name %></h1>

<% @category.places.each do |place| %>
	<br/>
	<li>
	<%= link_to place.name, place_path(place) %>
	<b>Address</b>	<%= place.address %>
	<b>Phone Number:</b>	<%= place.phone_number %>
	<b>Contact Mail:</b>	<%= place.contact_mail %>
	<b>Established at:</b> <%= place.established_at %>
	<b>Description: </b> <%= place.description %>
	<b>Category: </b> <%= place.category.name%>
	</li>
<%end%>

app/views/comments/_comment_form.html.erb
<% if current_customer.present? %>
<%= form_for [@place, @place.comments.build] do |f| %>
	<%= f.label :Comment%><br>
	<%= f.text_area :body, placeholder: 'comment', rows: 10 %><br><br>
	<%= f.hidden_field :place_id, :value => @place.id %>
	<%= f.submit 'Gonder'%>
<% end %>
<%end%>

app/views/comments/_comment_list.html.erb
<br/><br/>
<% @place.comments.each do |comment| %>
	<small><%= comment.customer.email %> says:</small>
	<p>
        <%= comment.body %>
        <% if current_customer.present? && comment.customer_id == current_customer.id %>
          <small><%= link_to "Delete", place_comment_path(@place, comment), method: :delete %></small>
        <% end %>
      </p>
<%end%>
<br/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vernewlace</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Customer Login</h1>
    <% if current_customer.present? %>
      <li><a href="#"><%= current_customer.email %></a></li>
      <li><%= link_to "Logout", destroy_customer_session_path, method: :delete %></li>
    <% else %>
      <li><%= link_to "Login", new_customer_session_path %></li>
      <li><%= link_to "Register", new_customer_registration_path %></li>
    <% end %>
    <h1>Owner Login</h1>
    <% if current_owner.present? %>
      <li><a href="#"><%= current_owner.email %></a></li>
      <li><%= link_to "Logout", destroy_owner_session_path, method: :delete %></li>
    <% else %>
      <li><%= link_to "Login", new_owner_session_path %></li>
      <li><%= link_to "Register", new_owner_registration_path %></li>
    <% end %>
    <%= render "flash" %>
    <%= yield %>
  </body>
</html>

app/views/places/_form.html.erb
<%= form_for @place do |f| %>
	<%= f.label :name %><br>
	<%= f.text_field :name, placeholder: 'name' %><br><br>
	<%= f.label :address%><br>
	<%= f.text_area :address, placeholder: 'adress', rows: 10 %><br><br>
	<%= f.label :phone_number%><br>
	<%= f.text_field :phone_number, placeholder: 'phone_number' %><br><br>
	<%= f.label :contact_mail%><br>
	<%= f.text_field :contact_mail, placeholder: 'contact_mail' %><br><br>
	<%= f.label :established_at%><br>
	<%= f.date_select :established_at, end_year: Date.today.year, start_year: 1950,  placeholder: 'established_at' %><br><br>
	<%= f.label :description%><br>
	<%= f.text_area :description, placeholder: 'description', rows: 10 %><br><br>
	<%= f.select :category_id, @categories %><br><br>

	<%= f.submit 'Gonder'%>
<% end %>

app/views/places/edit.html.erb
<h1>Editing <%= @place.name %> </h1>

<% if @place.errors.any? %>
	<h3>
	<%=  @place.errors.full_messages.join(", ") %>
	</h3>
<%end%>


<%= render "form" %>

app/views/places/index.html.erb
<% @places.each do |place| %>
	<br/>
	<li>
	<b>Name:</b>	<a href="<%= place_path(place) %>"><%= place.name %></a>
	<b>Address</b>	<%= place.address %>
	<b>Phone Number:</b>	<%= place.phone_number %>
	<b>Contact Mail:</b>	<%= place.contact_mail %>
	<b>Established at:</b> <%= place.established_at%>
	<b>Description:</b> <%= place.description %>
	<b>Category: </b> <%= place.category.name %>
	</li>
<%end%>
<br/>
<% if current_owner.present? %>
<%= link_to "Crate new place", new_place_path %>
<%end%>
<br/>
<br/>
<%= link_to "List Categories", categories_path %>
<br/>
<br/>

app/views/places/new.html.erb
<h1>Create a new Place</h1>

<% if @place.errors.any? %>
	<h3>
	<%=  @place.errors.full_messages.join(", ") %>
	</h3>
<%end%>

<%= render "form" %>

app/views/places/show.html.erb
Display Place
<br/><br/>
<li>
<b>Name:</b>	<%= @place.name %>
<b>Address</b>	<%= @place.address %>
<b>Phone Number:</b>	<%= @place.phone_number %>
<b>Contact Mail:</b>	<%= @place.contact_mail %>
<b>Established at:</b> <%= @place.established_at %>
<b>Description: </b> <%= @place.description %>
<b>Category: </b> <%= @place.category.name%>
</li>
<br/><br/>
<%= render 'reservations/form' %>
<br/><br/>
<%= render 'reservations/reservation_list' %><br/>
<b>Comments</b>
<%= render 'comments/comment_list' %>
<br/>
<%= render 'comments/comment_form' %>
<br/>
<%= link_to "Back to places list", places_path %>
<br/>
<% if current_owner.present? and current_owner.id == @place.owner_id %>
  <br/>
  <%= link_to "Edit place", edit_place_path(@place) %>
  <br/>
  <%= link_to "Delete place", place_path(@place), method: :delete, data:{confirm: "Emin misiniz?"} %>
<% end %>
<br/><br/><br/><br/>

app/views/reservations/_form.html.erb
<% if current_customer.present? %>
	<%= form_for [@place, Reservation.new] do |p| %>
		<%= p.label :date%><br>
		<%= p.date_select :date, start_year: Date.today.year, end_year: 2050 , placeholder: 'Reservation Date' %><br><br>
		<%= p.label :number_of_people %><br>
		<%= p.text_field :number_of_people, placeholder: 'Number of People' %><br><br>
		<%= p.submit 'Send'%>
	<% end %>
<%end%>

app/views/reservations/_reservation_list.html.erb
<% if current_owner.present? and current_owner.id == @place.owner_id %>
<br/><br/>	<b>Reservations</b>
	<% @place.reservations.each do |reserv| %>
		<small><%= reserv.customer.email %></small>
		<p>
	        <%= reserv.date %><br/><br/>
	        <%= reserv.number_of_people %>
	        <% if current_customer.present? && reserv.customer_id == current_customer.id %>
	          <small><%= link_to "Delete" %></small>
	        <% end %>
	      </p>
	<%end%>
	<br/>
<%end%>